#!/bin/sh

#NOMBRE Y RUTA DE BASE DE DATOS
db="orders"
path="d:\\xampp\\htdocs\\orders\\_support\\orders.sql"

#CREAR BASE DE DATOS
d:\\xampp\\mysql\\bin\\mysql -uroot -e "drop database \`$db\`;"

#CREAR BASE DE DATOS
d:\\xampp\\mysql\\bin\\mysql -uroot -e "create database if not exists \`$db\`;"

#VACIAR BASE DE DATOS
#MYSQL="/Applications/MAMP/Library/bin/mysql -h localhost -u root -proot -D $db"
#$MYSQL -BNe "show tables" | awk '{print "set foreign_key_checks=0; drop table `" $1 "`;"}' | $MYSQL
#unset MYSQL

#VOLCAR BASE DE DATOS
d:\\xampp\\mysql\\bin\\mysql -u root $db < $path;

#BUENA PRACTICA PARA TERMINAR SCRIPTS BASH: RETORNAR 0
exit 0